name: Generate Rotated Jobs

on:
  schedule:
    # Run at 9:00 AM UTC every day (generate 2000 jobs)
    - cron: '0 9 * * *'
    # Run at 1:00 PM UTC every day (generate 2000 jobs)
    - cron: '0 13 * * *'
  workflow_dispatch:
    inputs:
      job_count:
        description: 'Number of jobs to generate'
        required: false
        default: '2000'
        type: string

jobs:
  generate-jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate jobs
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}
          # One of the following providers is required. If Azure vars are set, the script will use Azure.
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            node generate-rotated-jobs.mjs ${{ github.event.inputs.job_count }}
          else
            node generate-rotated-jobs.mjs 2000
          fi
      
      - name: Commit state file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add rotation-state.json
          git diff --staged --quiet || git commit -m "Update rotation state after job generation [skip ci]"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      
      - name: Upload generation logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: job-generation-logs-${{ github.run_number }}
          path: |
            rotation-state.json
          retention-days: 30


